### ISSUE TITLE
kelp crashes after protocol update 18

### ISSUE THREAD

**Issue by minherc** [stellar/kelp#747] opened 2021-11-04 02:19 UTC
## Describe the bug

kelp crashes after protocol update 18

`
2021/11/04 04:58:22 ----------------------------------------------------------------------------------------------------
2021/11/04 04:58:22 Starting monitoring server on port 12223
2021/11/04 04:58:22 unable to get trades: error when fetching trades: error while fetching trades in SDEX (cursor=1570415431000): json: cannot unmarshal string into Go struct field Price._embedded.records.price.n of type int32
2021/11/04 04:58:22 not deleting any offers, deleteCycles (=1) needs to exceed deleteCyclesThreshold (=12)
2021/11/04 04:58:22 time taken for update loop: 165 millis
2021/11/04 04:58:22 not deleting any offers, fillTrackerDeleteCycles (=1) needs to exceed fillTrackerDeleteCyclesThreshold (=12)
2021/11/04 04:58:22 error when running an iteration of fill tracker: error when fetching trades: error while fetching trades in SDEX (cursor=1570415431000): json: cannot unmarshal string into Go struct field Price._embedded.records.price.n of type int32
2021/11/04 04:58:23 metric - successfully sent event metric of type 'update_offers'
2021/11/04 04:58:23 ----------------------------------------------------------------------------------------------------
`

## Expected behavior

also empty responce from horizon? 
https://horizon.stellar.org/accounts/GBMUUOW2BNIBWPN2DJIB55RWH3MWPDTSIEG22HXBK4MTBN3G4QQ23ZEV/offers

## Frequency

The frequency is:  always

## Steps To Reproduce

Start kelp with 18 

## Your Environment
kelp and core latest
updated yesterday

**Comment by minherc** [comment] 2021-11-04 02:31
this behavior on all kelp, I use the main horizon (https://horizon.stellar.org) and my own, does not work anywhere

**Comment by leighmcculloch** [comment] 2021-11-04 02:41
>json: cannot unmarshal string into Go struct field Price._embedded.records.price.n of type int32

Thanks for reporting. This error is a duplicate of #741.

**Closed by leighmcculloch** 2021-11-04 02:41 UTC
Labels: bug
