### ISSUE TITLE
If you Type in a > 1 percent spread, you can never delete it and go lower

### ISSUE THREAD

**Issue by msfeldstein** [stellar/kelp#231] opened 2019-08-07 22:38 UTC
In the levels fields, set a spread to 2.00%.  Leave the field then come back and try to edit or delete it you can add numbers after but can't delete the 2.00

**Comment by nikhilsaraf** [comment] 2019-09-06 09:13
dupe of #218

**Closed by nikhilsaraf** 2019-09-06 09:13 UTC
Labels: GUI, Kelpathon, bug
