### ISSUE TITLE
Critical BUG ⚠️

### ISSUE THREAD

**Issue by Fomin2402** [stellar/kelp#746] opened 2021-11-03 20:21 UTC
Got error from Kelp bot:

```
could not get last trade cursor from exchangeShim: error while fetching latest trade cursor in SDEX: json: cannot unmarshal string into Go struct field Price._embedded.records.price.n of type int32
```

I guess it happens because of stellar horizons updates with [breaking changes](https://stellar.org/developers-blog/protocol-18-upgrade-guide?locale=en)

```
The price fraction will represent its numerator and denominator values as strings because they will be 64 bit integers.
```

**Comment by syllik** [comment] 2021-11-03 20:25
Same problem. Checked on Win and Last Mac os builds.

**Comment by leighmcculloch** [comment] 2021-11-03 20:30
I think this is a duplicate of #741.

**Closed** 2021-11-03 20:37 UTC
Labels: bug
