### ISSUE TITLE
Some numeric fields cannot be reset during bot creation

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/kelp#227] opened 2019-08-07 01:42 UTC
## Describe the bug
Backspacing on fields like "Tick Interval" and "Maximum Randomized Tick Interval Delay" in advanced settings doesn't clear the field.

## Expected behavior
The bot should be able to clear the field entirely, and re-type the correct value. 

## Frequency
Always

## Steps To Reproduce
1. Click "Create Bot"
2. Go to "Advanced Settings"
3. Type something into "Tick Interval"
4. Try backspacing until the field is clear

**Comment by nikhilsaraf** [comment] 2019-09-06 09:13
dupe of #218

**Closed by nikhilsaraf** 2019-09-06 09:13 UTC
Labels: GUI, Kelpathon, bug
