### ISSUE TITLE
Kelp GUI Internal Testing - "Show Offers" and "Show Market" popups can't be closed

### ISSUE THREAD

**Issue by accordeiro** [stellar/kelp#388] opened 2020-03-04 01:00 UTC
## Describe the bug
Whenever I click on the `...` menu for bots, then click on `Show Offers`, I will get a popup that cannot be closed afterwards. 

## Expected behavior
I think the correct behavior in this situation is for the popup close button to be enabled.

## Frequency
Always.

## Possible Solution
Re-enable the default Mac "window close" (red) button.

## Your Environment
```
Kelp GUI v0.0.1-alpha (release/v0.0.x:v0.0.1-rc1)
OS: macOS 10.15.3
```

## Attachments

<img width="1059" alt="Screen Shot 2020-03-03 at 4 58 36 PM" src="https://user-images.githubusercontent.com/1952585/75834227-4430f180-5d70-11ea-9575-702d7c3c817c.png">

**Comment by nikhilsaraf** [comment] 2020-08-31 15:57
closing since this is a dupe of #359

**Closed by nikhilsaraf** 2020-08-31 15:57 UTC
Labels: bug
