### ISSUE TITLE
Let me see the edit screen while a bot is running

### ISSUE THREAD

**Issue by msfeldstein** [stellar/kelp#233] opened 2019-08-07 22:42 UTC
There is a lot of info in the bot edit screen that i'd like to see without having to stop the bot, such as the address of the source account, what my spreads are, etc.  I should be able to go into the screen while it's running even if everything is disabled.

**Comment by nikhilsaraf** [comment] 2019-08-16 08:23
dupe of #228

**Closed by nikhilsaraf** 2019-08-16 08:23 UTC
Labels: Kelpathon, feature request
