### ISSUE TITLE
allow increase of amounts when using "balanced" strategy

### ISSUE THREAD

**Issue by ddombrowsky** [stellar/kelp#415] opened 2020-05-05 15:11 UTC
## Desired Behavior

When using the "balanced" strategy, it does not appear to be possible to increase the amounts placed in each order.  The config file suggests that changing `VIRTUAL_BALANCE_BASE` and `VIRTUAL_BALANCE_QUOTE` will do this, but changing this to anything but 0.0 throws off the price by an order of magnitude.

Right now, each order is placed for about 0.2 XLM, even though I have hundreds of XLM available in the account.  I was hoping to increase that without having to hack the code.

## Impact

I'm looking for some kind of multiplier that will crease the size of each posted order.  If it exists, please point me to where it is documented in the example configuration.

This will allow me to increase the size of each order.

**Comment by ddombrowsky** [comment] 2020-05-05 15:13
For example, most orders are placed with a base amount of `0.00000150`:

```
2020/05/05 11:11:57 offer | buy  | level=29 | curPriceQuote=118137.67764953 | curAmtBase=0.00000160 | pruning=false
2020/05/05 11:11:57 offer | buy  | level=30 | curPriceQuote=117192.07781554 | curAmtBase=0.00000160 | pruning=false
2020/05/05 11:11:57 offer | sell | level=1 | curPriceQuote=124249.34619169 | curAmtBase=0.00000150 | pruning=false
2020/05/05 11:11:57 offer | sell | level=2 | curPriceQuote=124369.50127570 | curAmtBase=0.00000150 | pruning=false
```

I'm willing to risk more than that, and would like that to be configurable.

**Comment by nikhilsaraf** [comment] 2020-05-05 15:19
@ddombrowsky that is by design and can be seen as one of the limitations of the balanced strategy. The amount restriction allows a specific invariant to always be true: that the account will *never* run out of either asset.

I have a version of the balanced strategy that allows one to specify the amounts. However this is unreleased yet and I do not recommend using this on the public network. I have to yet write a walkthrough about this strategy. You can find it in a [branch in my private fork here](https://github.com/nikhilsaraf/kelp/tree/swing_strategy).

If you have any questions about it feel free to open a new issue titled swing strategy. Closing this issue out for now, feel free to reopen if necessary.

**Closed by nikhilsaraf** 2020-05-05 15:19 UTC
Labels: feature request

**Comment by ddombrowsky** [comment] 2020-05-05 15:39
@nikhilsaraf OK.  I'll await the new strategy.

Until then, I'll just hard-code it: https://github.com/ddombrowsky/kelp/commit/fef2bd8e16a7697bf1fb84c831b18a0808d82759

**Comment by nikhilsaraf** [comment] 2020-05-05 17:19
I would strongly advise against hardcoding the amount since that will affect the price the bot will offer, which could be significantly skewed from the market price.

With your modification it is unlikely to do what you intend for it to do.
